# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8e75d2d6eb24f386605f0f85c8fb527985f850b103c1ac7f744404bf318a3a7b19e3f8908d73cc86481cb028f15f74ddd32dc92b9fc7085eef5dfb9bbfa766

test:
  secret_key_base: 03100e7d621edad51aa36abbc67d756b91b266ae41e1138eb4607b7c0e84fad72616f2c9f0a0946af07fb756d1e21ba2256208e856421f6339f2628a0e8e384b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
